//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Privatezilla.Locales {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Privatezilla.Locales.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply selected ähnelt.
        /// </summary>
        internal static string BtnDoPS {
            get {
                return ResourceManager.GetString("BtnDoPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analyze ähnelt.
        /// </summary>
        internal static string BtnSettingsAnalyze {
            get {
                return ResourceManager.GetString("BtnSettingsAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply selected ähnelt.
        /// </summary>
        internal static string BtnSettingsDo {
            get {
                return ResourceManager.GetString("BtnSettingsDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Revert selected ähnelt.
        /// </summary>
        internal static string BtnSettingsUndo {
            get {
                return ResourceManager.GetString("BtnSettingsUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check for updates ähnelt.
        /// </summary>
        internal static string CheckRelease {
            get {
                return ResourceManager.GetString("CheckRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View code ähnelt.
        /// </summary>
        internal static string ChkCodePS {
            get {
                return ResourceManager.GetString("ChkCodePS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Setting ähnelt.
        /// </summary>
        internal static string columnSetting {
            get {
                return ResourceManager.GetString("columnSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die State ähnelt.
        /// </summary>
        internal static string columnState {
            get {
                return ResourceManager.GetString("columnState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get community package ähnelt.
        /// </summary>
        internal static string CommunityPkg {
            get {
                return ResourceManager.GetString("CommunityPkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Short Guide ähnelt.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info about a setting: \r\nMove the cursor over a setting to view a brief explanation
        ///                                           \r\nAnalyze (Button): Determines which settings are enabled and configured on your system or not. NO system changes are done yet! 
        ///                                           \r\nApply selected (Button): This will enable all selected settings.
        ///                                           \r\nRevert selected (Button): This will restore the default Windows 10 settings.
        ///              [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string helpApp {
            get {
                return ResourceManager.GetString("helpApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///The open source Windows 10 privacy settings app.
        ///
        ///This is in no way related to Microsoft and a completely independent project.
        ///
        ///All infos and credits about this project on
        ///\tgithub.com/builtbybel/privatezilla
        ///
        ///You can also follow me on
        ///\ttwitter.com/builtbybel
        ///
        ///(C#) 2021, Builtbybel ähnelt.
        /// </summary>
        internal static string infoApp {
            get {
                return ResourceManager.GetString("infoApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scripts ähnelt.
        /// </summary>
        internal static string LblPS {
            get {
                return ResourceManager.GetString("LblPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply PowerShell Script ähnelt.
        /// </summary>
        internal static string LblPSHeader {
            get {
                return ResourceManager.GetString("LblPSHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string LblSettings {
            get {
                return ResourceManager.GetString("LblSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press Analyze to check for configured settings. ähnelt.
        /// </summary>
        internal static string LblStatus {
            get {
                return ResourceManager.GetString("LblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are running Privatezilla on a system older than Windows 10. Privatezilla is limited to Windows 10 ONLY. ähnelt.
        /// </summary>
        internal static string msgAppCompatibility {
            get {
                return ResourceManager.GetString("msgAppCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please switch to code view. ähnelt.
        /// </summary>
        internal static string msgPSSave {
            get {
                return ResourceManager.GetString("msgPSSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a script. ähnelt.
        /// </summary>
        internal static string msgPSSelect {
            get {
                return ResourceManager.GetString("msgPSSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die has been successfully executed ähnelt.
        /// </summary>
        internal static string msgPSSuccess {
            get {
                return ResourceManager.GetString("msgPSSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        internal static string PSBack {
            get {
                return ResourceManager.GetString("PSBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import script ähnelt.
        /// </summary>
        internal static string PSImport {
            get {
                return ResourceManager.GetString("PSImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What does this script do?\r\n ähnelt.
        /// </summary>
        internal static string PSInfo {
            get {
                return ResourceManager.GetString("PSInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visit Marketplace ähnelt.
        /// </summary>
        internal static string PSMarketplace {
            get {
                return ResourceManager.GetString("PSMarketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save current script as new preset script ähnelt.
        /// </summary>
        internal static string PSSaveAs {
            get {
                return ResourceManager.GetString("PSSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are using an unoffical version of Privatezilla. ähnelt.
        /// </summary>
        internal static string releaseUnofficial {
            get {
                return ResourceManager.GetString("releaseUnofficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is a new version available # ähnelt.
        /// </summary>
        internal static string releaseUpdateAvailable {
            get {
                return ResourceManager.GetString("releaseUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \r\nDo you want to open the @github/releases page? ähnelt.
        /// </summary>
        internal static string releaseUpdateAvailableURL {
            get {
                return ResourceManager.GetString("releaseUpdateAvailableURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \r\nYour are using version # ähnelt.
        /// </summary>
        internal static string releaseUpdateYourVersion {
            get {
                return ResourceManager.GetString("releaseUpdateYourVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are currently no updates available. ähnelt.
        /// </summary>
        internal static string releaseUpToDate {
            get {
                return ResourceManager.GetString("releaseUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App permissions ähnelt.
        /// </summary>
        internal static string rootSettingsApps {
            get {
                return ResourceManager.GetString("rootSettingsApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bloatware ähnelt.
        /// </summary>
        internal static string rootSettingsBloatware {
            get {
                return ResourceManager.GetString("rootSettingsBloatware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debloat Windows 10 ähnelt.
        /// </summary>
        internal static string rootSettingsBloatwareInfo {
            get {
                return ResourceManager.GetString("rootSettingsBloatwareInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cortana ähnelt.
        /// </summary>
        internal static string rootSettingsCortana {
            get {
                return ResourceManager.GetString("rootSettingsCortana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows Defender ähnelt.
        /// </summary>
        internal static string rootSettingsDefender {
            get {
                return ResourceManager.GetString("rootSettingsDefender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microsoft Edge ähnelt.
        /// </summary>
        internal static string rootSettingsEdge {
            get {
                return ResourceManager.GetString("rootSettingsEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gaming ähnelt.
        /// </summary>
        internal static string rootSettingsGaming {
            get {
                return ResourceManager.GetString("rootSettingsGaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy ähnelt.
        /// </summary>
        internal static string rootSettingsPrivacy {
            get {
                return ResourceManager.GetString("rootSettingsPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Security ähnelt.
        /// </summary>
        internal static string rootSettingsSecurity {
            get {
                return ResourceManager.GetString("rootSettingsSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Updates ähnelt.
        /// </summary>
        internal static string rootSettingsUpdates {
            get {
                return ResourceManager.GetString("rootSettingsUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app access to account info ähnelt.
        /// </summary>
        internal static string settingsAppsAccountInfo {
            get {
                return ResourceManager.GetString("settingsAppsAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app notifications ähnelt.
        /// </summary>
        internal static string settingsAppsAppNotifications {
            get {
                return ResourceManager.GetString("settingsAppsAppNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Action Center in Windows 10 collects and shows notifications and alerts from traditional Windows applications and system notifications, alongside those generated from modern apps.\nNotifications are then grouped in the Action Center by app and time.\nThis setting will disable all notifications from apps and other senders in settings. ähnelt.
        /// </summary>
        internal static string settingsAppsAppNotificationsInfo {
            get {
                return ResourceManager.GetString("settingsAppsAppNotificationsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable apps running in background ähnelt.
        /// </summary>
        internal static string settingsAppsBackgroundApps {
            get {
                return ResourceManager.GetString("settingsAppsBackgroundApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows 10 apps have no more permission to run in the background so they can&apos;t update their live tiles, fetch new data, and receive notifications. ähnelt.
        /// </summary>
        internal static string settingsAppsBackgroundAppsInfo {
            get {
                return ResourceManager.GetString("settingsAppsBackgroundAppsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app access to calendar ähnelt.
        /// </summary>
        internal static string settingsAppsCalendar {
            get {
                return ResourceManager.GetString("settingsAppsCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app access to call ähnelt.
        /// </summary>
        internal static string settingsAppsCall {
            get {
                return ResourceManager.GetString("settingsAppsCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app access to call history ähnelt.
        /// </summary>
        internal static string settingsAppsCallHistory {
            get {
                return ResourceManager.GetString("settingsAppsCallHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app access to camera ähnelt.
        /// </summary>
        internal static string settingsAppsCamera {
            get {
                return ResourceManager.GetString("settingsAppsCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app access to cellular data ähnelt.
        /// </summary>
        internal static string settingsAppsCellularData {
            get {
                return ResourceManager.GetString("settingsAppsCellularData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Some Windows 10 devices have a SIM card and/or eSIM in them that lets you connect to a cellular data network (aka: LTE or Broadband), so you can get online in more places by using a cellular signal.\nIf you do not want any apps to be allowed to use cellular data, you can disable it with this setting. ähnelt.
        /// </summary>
        internal static string settingsAppsCellularDataInfo {
            get {
                return ResourceManager.GetString("settingsAppsCellularDataInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app access to contacts ähnelt.
        /// </summary>
        internal static string settingsAppsContacts {
            get {
                return ResourceManager.GetString("settingsAppsContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app access to diagnostics ähnelt.
        /// </summary>
        internal static string settingsAppsDiagnosticInformation {
            get {
                return ResourceManager.GetString("settingsAppsDiagnosticInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app access to documents ähnelt.
        /// </summary>
        internal static string settingsAppsDocuments {
            get {
                return ResourceManager.GetString("settingsAppsDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app access to email ähnelt.
        /// </summary>
        internal static string settingsAppsEmail {
            get {
                return ResourceManager.GetString("settingsAppsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app access to eye tracking ähnelt.
        /// </summary>
        internal static string settingsAppsEyeGaze {
            get {
                return ResourceManager.GetString("settingsAppsEyeGaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app access to eye-gaze-based interaction ähnelt.
        /// </summary>
        internal static string settingsAppsEyeGazeInfo {
            get {
                return ResourceManager.GetString("settingsAppsEyeGazeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app access to file system ähnelt.
        /// </summary>
        internal static string settingsAppsFileSystem {
            get {
                return ResourceManager.GetString("settingsAppsFileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This setting will disable app access to file system. Some apps may be restricted in their function or may no longer work at all. ähnelt.
        /// </summary>
        internal static string settingsAppsFileSystemInfo {
            get {
                return ResourceManager.GetString("settingsAppsFileSystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app access to messaging ähnelt.
        /// </summary>
        internal static string settingsAppsMessaging {
            get {
                return ResourceManager.GetString("settingsAppsMessaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app access to microphone ähnelt.
        /// </summary>
        internal static string settingsAppsMicrophone {
            get {
                return ResourceManager.GetString("settingsAppsMicrophone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app access to motion ähnelt.
        /// </summary>
        internal static string settingsAppsMotion {
            get {
                return ResourceManager.GetString("settingsAppsMotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app access to notifications ähnelt.
        /// </summary>
        internal static string settingsAppsNotification {
            get {
                return ResourceManager.GetString("settingsAppsNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app access to other devices ähnelt.
        /// </summary>
        internal static string settingsAppsOtherDevices {
            get {
                return ResourceManager.GetString("settingsAppsOtherDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app access to pictures ähnelt.
        /// </summary>
        internal static string settingsAppsPictures {
            get {
                return ResourceManager.GetString("settingsAppsPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app access to radios ähnelt.
        /// </summary>
        internal static string settingsAppsRadios {
            get {
                return ResourceManager.GetString("settingsAppsRadios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app access to tasks ähnelt.
        /// </summary>
        internal static string settingsAppsTasks {
            get {
                return ResourceManager.GetString("settingsAppsTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable tracking of app starts ähnelt.
        /// </summary>
        internal static string settingsAppsTrackingApps {
            get {
                return ResourceManager.GetString("settingsAppsTrackingApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This allows you to quickly have access to your list of Most used apps both in the Start menu and when you search your device.&quot; ähnelt.
        /// </summary>
        internal static string settingsAppsTrackingAppsInfo {
            get {
                return ResourceManager.GetString("settingsAppsTrackingAppsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable app access to videos ähnelt.
        /// </summary>
        internal static string settingsAppsVideos {
            get {
                return ResourceManager.GetString("settingsAppsVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove all built-in apps ähnelt.
        /// </summary>
        internal static string settingsBloatwareRemoveUWPAll {
            get {
                return ResourceManager.GetString("settingsBloatwareRemoveUWPAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This will remove all built-in apps except Microsoft Store. ähnelt.
        /// </summary>
        internal static string settingsBloatwareRemoveUWPAllInfo {
            get {
                return ResourceManager.GetString("settingsBloatwareRemoveUWPAllInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove all built-in apps except defaults ähnelt.
        /// </summary>
        internal static string settingsBloatwareRemoveUWPDefaults {
            get {
                return ResourceManager.GetString("settingsBloatwareRemoveUWPDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This will remove all built-in apps except the following:\nMicrosoft Store\nApp Installer\nCalendar\nMail\nCalculator\nCamera\nSkype\nGroove Music\nMaps\nPaint 3D\nYour Phone\nPhotos\nSticky Notes\nWeather\nXbox ähnelt.
        /// </summary>
        internal static string settingsBloatwareRemoveUWPDefaultsInfo {
            get {
                return ResourceManager.GetString("settingsBloatwareRemoveUWPDefaultsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Bing in Windows Search ähnelt.
        /// </summary>
        internal static string settingsCortanaDisableBing {
            get {
                return ResourceManager.GetString("settingsCortanaDisableBing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows 10, by default, sends everything you search for in the Start Menu to their servers to give you results from Bing search. ähnelt.
        /// </summary>
        internal static string settingsCortanaDisableBingInfo {
            get {
                return ResourceManager.GetString("settingsCortanaDisableBingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Cortana ähnelt.
        /// </summary>
        internal static string settingsCortanaDisableCortana {
            get {
                return ResourceManager.GetString("settingsCortanaDisableCortana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cortana is Microsoft&apos;s virtual assistant that comes integrated into Windows 10.\nThis setting will disable Cortana permanently and prevent it from recording and storing your search habits and history. ähnelt.
        /// </summary>
        internal static string settingsCortanaDisableCortanaInfo {
            get {
                return ResourceManager.GetString("settingsCortanaDisableCortanaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uninstall Cortana ähnelt.
        /// </summary>
        internal static string settingsCortanaUninstallCortana {
            get {
                return ResourceManager.GetString("settingsCortanaUninstallCortana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This will uninstall the new Cortana app on Windows 10, version 2004. ähnelt.
        /// </summary>
        internal static string settingsCortanaUninstallCortanaInfo {
            get {
                return ResourceManager.GetString("settingsCortanaUninstallCortanaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable SmartScreen for Store Apps ähnelt.
        /// </summary>
        internal static string settingsDefenderDisableSmartScreenStore {
            get {
                return ResourceManager.GetString("settingsDefenderDisableSmartScreenStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows Defender SmartScreen Filter helps protect your device by checking web content (URLs) that Microsoft Store apps use. ähnelt.
        /// </summary>
        internal static string settingsDefenderDisableSmartScreenStoreInfo {
            get {
                return ResourceManager.GetString("settingsDefenderDisableSmartScreenStoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable AutoFill for credit cards ähnelt.
        /// </summary>
        internal static string settingsEdeAutoFillCredit {
            get {
                return ResourceManager.GetString("settingsEdeAutoFillCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microsoft Edge&apos;s AutoFill feature lets users auto complete credit card information in web forms using previously stored information. ähnelt.
        /// </summary>
        internal static string settingsEdeAutoFillCreditInfo {
            get {
                return ResourceManager.GetString("settingsEdeAutoFillCreditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prevent Edge running in background ähnelt.
        /// </summary>
        internal static string settingsEdgeBackground {
            get {
                return ResourceManager.GetString("settingsEdgeBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On the new Chromium version of Microsoft Edge, extensions and other services can keep the browser running in the background even after it&apos;s closed. ähnelt.
        /// </summary>
        internal static string settingsEdgeBackgroundInfo {
            get {
                return ResourceManager.GetString("settingsEdgeBackgroundInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block Installation of New Microsoft Edge ähnelt.
        /// </summary>
        internal static string settingsEdgeBlockEdgeRollout {
            get {
                return ResourceManager.GetString("settingsEdgeBlockEdgeRollout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This will block Windows 10 Update Force Installing of the new Chromium-based Microsoft Edge web browser if it&apos;s not installed already on the device. ähnelt.
        /// </summary>
        internal static string settingsEdgeBlockEdgeRolloutInfo {
            get {
                return ResourceManager.GetString("settingsEdgeBlockEdgeRolloutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable synchronization of data ähnelt.
        /// </summary>
        internal static string settingsEdgeDisableSync {
            get {
                return ResourceManager.GetString("settingsEdgeDisableSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This setting will disable synchronization of data using Microsoft sync services. ähnelt.
        /// </summary>
        internal static string settingsEdgeDisableSyncInfo {
            get {
                return ResourceManager.GetString("settingsEdgeDisableSyncInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Game Bar features ähnelt.
        /// </summary>
        internal static string settingsGamingGameBar {
            get {
                return ResourceManager.GetString("settingsGamingGameBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This setting will disable the Windows Game Recording and Broadcasting. ähnelt.
        /// </summary>
        internal static string settingsGamingGameBarInfo {
            get {
                return ResourceManager.GetString("settingsGamingGameBarInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This will turn off tailored experiences with relevant tips and recommendations by using your diagnostics data. Many people would call this telemetry, or even spying. ähnelt.
        /// </summary>
        internal static string settingsGamingGameBarInfoInfo {
            get {
                return ResourceManager.GetString("settingsGamingGameBarInfoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block suggested apps in Start ähnelt.
        /// </summary>
        internal static string settingsPrivacyBlockSuggestedApps {
            get {
                return ResourceManager.GetString("settingsPrivacyBlockSuggestedApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This will block the Suggested Apps that occasionally appear on the Start menu. ähnelt.
        /// </summary>
        internal static string settingsPrivacyBlockSuggestedAppsInfo {
            get {
                return ResourceManager.GetString("settingsPrivacyBlockSuggestedAppsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prevent using diagnostic data ähnelt.
        /// </summary>
        internal static string settingsPrivacyDiagnosticData {
            get {
                return ResourceManager.GetString("settingsPrivacyDiagnosticData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This will turn off tailored experiences with relevant tips and recommendations by using your diagnostics data. Many people would call this telemetry, or even spying. ähnelt.
        /// </summary>
        internal static string settingsPrivacyDiagnosticDataInfo {
            get {
                return ResourceManager.GetString("settingsPrivacyDiagnosticDataInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Advertising ID for Relevant Ads ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableAds {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows 10 comes integrated with advertising. Microsoft assigns a unique identificator to track your activity in the Microsoft Store and on UWP apps to target you with relevant ads. ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableAdsInfo {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableAdsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Windows Hello Biometrics ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableBiometrics {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableBiometrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows Hello biometrics lets you sign in to your devices, apps, online services, and networks using your face, iris, or fingerprint. ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableBiometricsInfo {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableBiometricsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Customer Experience Program ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableCEIP {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableCEIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Customer Experience Improvement Program (CEIP) is a feature that comes enabled by default on Windows 10, and it secretly collects and submits hardware and software usage information to Microsoft. ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableCEIPInfo {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableCEIPInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Compatibility Telemetry ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableCompTelemetry {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableCompTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This process is periodically collecting a variety of technical data about your computer and its performance and sending it to Microsoft for its Windows Customer Experience Improvement Program. ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableCompTelemetryInfo {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableCompTelemetryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do not show feedback notifications ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableFeedback {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows 10 may also pop up from time to time and ask for feedback. ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableFeedbackInfo {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableFeedbackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Help Experience Program ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableHEIP {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableHEIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Help Experience Improvement Program (HEIP) collects and send to Microsoft information about how you use Windows Help. This might reveal what problems you are having with your computer. ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableHEIPInfo {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableHEIPInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Location tracking ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableLocation {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wherever you go, Windows 10 knows you&apos;re there. When Location Tracking is turned on, Windows and its apps are allowed to detect the current location of your computer or device. ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableLocationInfo {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableLocationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Settings Experimentation ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableMSExperiments {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableMSExperiments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In certain builds of Windows 10, users could let Microsoft experiment with the system to study user preferences or device behavior. This allows Microsoft to “conduct experiments” with the settings on your PC and should be disabled with this setting. ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableMSExperimentsInfo {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableMSExperimentsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Telemetry ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableTelemetry {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This will prevent Windows from collecting usage information and setting diagnostic data to Basic, which is the lowest level available for all consumer versions of Windows 10.\nThe services diagtrack &amp; dmwappushservice will also be disabled.\nNOTE: Diagnostic Data must be set to Full to get preview builds from Windows-Insider-Program! ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableTelemetryInfo {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableTelemetryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Timeline feature ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableTimeline {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This collects a history of activities you&apos;ve performed, including files you&apos;ve opened and web pages you&apos;ve viewed in Edge.\nIf Timeline isn’t for you, or you simply don’t want Windows 10 collecting your sensitive activities and information, you can disable Timeline completely with this setting.\nNote: A system reboot is required for the changes to take effect. ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableTimelineInfo {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableTimelineInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Windows Tips ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableTips {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You will no longer see Windows Tips, e.g. Spotlight and Consumer Features, Feedback Notifications etc. ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableTipsInfo {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableTipsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Ads and Links on Lock Screen ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableTipsLockScreen {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableTipsLockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This setting will set your lock screen background options to a picture and turn off tips, fun facts and tricks from Microsoft. ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableTipsLockScreenInfo {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableTipsLockScreenInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Wi-Fi Sense ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableWiFi {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableWiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You should at least stop your PC from sending your Wi-Fi password. ähnelt.
        /// </summary>
        internal static string settingsPrivacyDisableWiFiInfo {
            get {
                return ResourceManager.GetString("settingsPrivacyDisableWiFiInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Get Even More Out of Windows ähnelt.
        /// </summary>
        internal static string settingsPrivacyGetMoreOutOfWindows {
            get {
                return ResourceManager.GetString("settingsPrivacyGetMoreOutOfWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recent Windows 10 versions occasionally display a nag screen &quot;Get Even More Out of Windows&quot; when you sign-in to your user account. If you find it annoying, you can disable it with this setting. ähnelt.
        /// </summary>
        internal static string settingsPrivacyGetMoreOutOfWindowsInfo {
            get {
                return ResourceManager.GetString("settingsPrivacyGetMoreOutOfWindowsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prevent using handwriting data ähnelt.
        /// </summary>
        internal static string settingsPrivacyHandwritingData {
            get {
                return ResourceManager.GetString("settingsPrivacyHandwritingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you don’t want Windows to know and record all unique words that you use, like names and professional jargon, just enable this setting. ähnelt.
        /// </summary>
        internal static string settingsPrivacyHandwritingDataInfo {
            get {
                return ResourceManager.GetString("settingsPrivacyHandwritingDataInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block automatic Installation of apps ähnelt.
        /// </summary>
        internal static string settingsPrivacyInstalledApps {
            get {
                return ResourceManager.GetString("settingsPrivacyInstalledApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When you sign-in to a new Windows 10 profile or device for the first time, chance is that you notice several third-party applications and games listed prominently in the Start menu.\nThis setting will block automatic Installation of suggested Windows 10 apps. ähnelt.
        /// </summary>
        internal static string settingsPrivacyInstalledAppsInfo {
            get {
                return ResourceManager.GetString("settingsPrivacyInstalledAppsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Inventory Collector ähnelt.
        /// </summary>
        internal static string settingsPrivacyInventoryCollector {
            get {
                return ResourceManager.GetString("settingsPrivacyInventoryCollector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Inventory Collector inventories applications files devices and drivers on the system and sends the information to Microsoft. This information is used to help diagnose compatibility problems.\nNote: This setting has no effect if the Customer Experience Improvement Program is turned off. The Inventory Collector will be off. ähnelt.
        /// </summary>
        internal static string settingsPrivacyInventoryCollectorInfo {
            get {
                return ResourceManager.GetString("settingsPrivacyInventoryCollectorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block suggested content in Settings app ähnelt.
        /// </summary>
        internal static string settingsPrivacySuggestedContent {
            get {
                return ResourceManager.GetString("settingsPrivacySuggestedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To help new Windows 10 users to learn new features of Windows 10, Microsoft has started showing suggested content via a huge banner in Windows 10 Setting Apps. ähnelt.
        /// </summary>
        internal static string settingsPrivacySuggestedContentInfo {
            get {
                return ResourceManager.GetString("settingsPrivacySuggestedContentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable password reveal button ähnelt.
        /// </summary>
        internal static string settingsSecurityDisablePassword {
            get {
                return ResourceManager.GetString("settingsSecurityDisablePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password reveal button can be used to display an entered password and should be disabled with this setting. ähnelt.
        /// </summary>
        internal static string settingsSecurityDisablePasswordInfo {
            get {
                return ResourceManager.GetString("settingsSecurityDisablePasswordInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable DRM in Windows Media Player ähnelt.
        /// </summary>
        internal static string settingsSecurityWindowsDRM {
            get {
                return ResourceManager.GetString("settingsSecurityWindowsDRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If the Windows Media Digital Rights Management should not get access to the Internet (or intranet) for license acquisition and security upgrades, you can prevent it with this setting. ähnelt.
        /// </summary>
        internal static string settingsSecurityWindowsDRMInfo {
            get {
                return ResourceManager.GetString("settingsSecurityWindowsDRMInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Block major Windows updates ähnelt.
        /// </summary>
        internal static string settingsUpdatesBlockMajorUpdates {
            get {
                return ResourceManager.GetString("settingsUpdatesBlockMajorUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This setting called &quot;TargetReleaseVersionInfo&quot; prevents Windows 10 feature updates from being installed until the specified version reaches the end of support.\nIt will specify your currently used Windows 10 version as the target release version of Windows 10 that you wish the system to be on (supports only Pro and enterprise versions). ähnelt.
        /// </summary>
        internal static string settingsUpdatesBlockMajorUpdatesInfo {
            get {
                return ResourceManager.GetString("settingsUpdatesBlockMajorUpdatesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable safeguards for feature updates ähnelt.
        /// </summary>
        internal static string settingsUpdatesDisableSafeguards {
            get {
                return ResourceManager.GetString("settingsUpdatesDisableSafeguards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microsoft uses diagnostic data to determine whether devices that use Windows Update are ready for a feature update in order to ensure a smooth experience.\nWhen Microsoft determines a device is not ready to update due to a known issue, a safeguard hold (also known as a compatibility hold or update block) is generated to delay the device&apos;s upgrade and protect the end-user experience.\nThis setting will opt out of safeguard protections allowing you to bypass any feature upgrade blocks. ähnelt.
        /// </summary>
        internal static string settingsUpdatesDisableSafeguardsInfo {
            get {
                return ResourceManager.GetString("settingsUpdatesDisableSafeguardsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable forced Windows updates ähnelt.
        /// </summary>
        internal static string settingsUpdatesDisableUpdates {
            get {
                return ResourceManager.GetString("settingsUpdatesDisableUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This will notify when updates are available, and you decide when to install them. ähnelt.
        /// </summary>
        internal static string settingsUpdatesDisableUpdatesInfo {
            get {
                return ResourceManager.GetString("settingsUpdatesDisableUpdatesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Windows updates sharing ähnelt.
        /// </summary>
        internal static string settingsUpdatesUpdateSharing {
            get {
                return ResourceManager.GetString("settingsUpdatesUpdateSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows 10 lets you download updates from several sources to speed up the process of updating the operating system. This will disable sharing your files by others and exposing your IP address to random computers. ähnelt.
        /// </summary>
        internal static string settingsUpdatesUpdateSharingInfo {
            get {
                return ResourceManager.GetString("settingsUpdatesUpdateSharingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        internal static string statusDoPSApply {
            get {
                return ResourceManager.GetString("statusDoPSApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Processing ähnelt.
        /// </summary>
        internal static string statusDoPSProcessing {
            get {
                return ResourceManager.GetString("statusDoPSProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please wait ... ähnelt.
        /// </summary>
        internal static string statusDoWait {
            get {
                return ResourceManager.GetString("statusDoWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not applied ähnelt.
        /// </summary>
        internal static string statusFailedApply {
            get {
                return ResourceManager.GetString("statusFailedApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not configured ähnelt.
        /// </summary>
        internal static string statusFailedConfigure {
            get {
                return ResourceManager.GetString("statusFailedConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analysis complete. ähnelt.
        /// </summary>
        internal static string statusFinishAnalyze {
            get {
                return ResourceManager.GetString("statusFinishAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Applying complete. ähnelt.
        /// </summary>
        internal static string statusFinishApply {
            get {
                return ResourceManager.GetString("statusFinishApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reverting complete. ähnelt.
        /// </summary>
        internal static string statusFinishUndo {
            get {
                return ResourceManager.GetString("statusFinishUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Applied ähnelt.
        /// </summary>
        internal static string statusSuccessApply {
            get {
                return ResourceManager.GetString("statusSuccessApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configured ähnelt.
        /// </summary>
        internal static string statusSuccessConfigure {
            get {
                return ResourceManager.GetString("statusSuccessConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to revert all selected settings to Windows 10 default state? ähnelt.
        /// </summary>
        internal static string statusUndoSettings {
            get {
                return ResourceManager.GetString("statusUndoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configured: ähnelt.
        /// </summary>
        internal static string summaryConfigured {
            get {
                return ResourceManager.GetString("summaryConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summary ähnelt.
        /// </summary>
        internal static string summaryInfo {
            get {
                return ResourceManager.GetString("summaryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not Configured: ähnelt.
        /// </summary>
        internal static string summaryNotConfigured {
            get {
                return ResourceManager.GetString("summaryNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selected: ähnelt.
        /// </summary>
        internal static string summarySelected {
            get {
                return ResourceManager.GetString("summarySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome to the Scripting Editor, which allows you to apply third-party script files and custom settings in form of PowerShell scripts and templates (bundled scripts).
        ///
        ///Select a script to view it&apos;s description.
        ///
        ///To check the code for vulnerabilities click on &quot;View code&quot;.
        ///
        ///To obtain new objects (templates, scripts etc.) visit the Marketplace in the upper right menu. ähnelt.
        /// </summary>
        internal static string TxtPSInfo {
            get {
                return ResourceManager.GetString("TxtPSInfo", resourceCulture);
            }
        }
    }
}
